source :rubygems
# gem 'berkshelf', '1.1.6' # depends 'chef', '= 10.16.2'
#, git: 'git://github.com/RiotGames/berkshelf.git', ref: '9abe8c0b'
# gem 'ffi', '1.0.9'
# gem 'chef', '11.2.0' 
#gem 'em-winrm'
#gem 'veewee'
#gem 'vagrant', github: 'mitchellh/vagrant', ref: 'f7491e2c6' # Feb 13, 2013
gem 'vagrant', github: 'hh/vagrant', ref: 'depend_on_net-ssh_2.6'
gem 'berkshelf', github: 'hh/berkshelf', ref: 'depend_on_chef_11.4.0'
#gem 'vagrant-windows'
# gem 'vagrant', path: '/home/hh/chef/vagrant'
# gem 'berkshelf', path: '/home/hh/chef/berkshelf'
gem 'pry'
gem 'map_by_method'
